# Generated by Django 3.1.2 on 2021-02-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_auto_20210219_2129"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=9, verbose_name="Rental price"
            ),
            preserve_default=False,
        ),
    ]
