site_name: Book Rest API
site_description: Example to usages Django Rest Framework
repo_url: https://github.com/christianalcantara/book_backend
site_dir: site
copyright: Copyright &copy; 2021, <a href="https://github.com/christianalcantara">Christian Douglas Alcântara</a>.
dev_addr: 0.0.0.0:8000

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
