# Generated by Django 3.1.2 on 2021-02-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0002_auto_20210221_0609"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Catalog",
        ),
    ]
