# Generated by Django 3.1.2 on 2021-02-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0003_delete_catalog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Fee",
        ),
    ]
