# Generated by Django 3.1.2 on 2021-02-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_client",
            field=models.BooleanField(default=False, verbose_name="Active"),
        ),
    ]
