# Generated by Django 3.1.2 on 2021-02-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_is_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_client",
        ),
        migrations.AddField(
            model_name="user",
            name="is_customer",
            field=models.BooleanField(default=False, verbose_name="Customer"),
        ),
    ]
